export const PASSWORD_VALIDATION_ERROR_KEY = 'PASSWORD_VALIDATION_ERROR';

export const PASSWORD_MIN_LEN_ERROR_KEY = 'PASSWORD_MIN_LEN_ERROR';
export const PASSWORD_MAX_LEN_ERROR_KEY = 'PASSWORD_MAX_LEN_ERROR';
export const PASSWORD_SPACIAL_CHAR_ERROR_KEY = 'PASSWORD_SPACIAL_CHAR_ERROR';
